[package]
name = "stabby-abi"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
stabby-macros = { path = "../stabby-macros/" }
