[package]
name = "stabby"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }

[features]
default = ["std"]
std = ["alloc"]
alloc = ["stabby-abi/alloc"]

[dependencies]
stabby-abi = { path = "../stabby-abi/", version = "0.1.0" }
stabby-macros = { path = "../stabby-macros/", version = "0.1.0" }
